apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp-cert
spec:
  secretName: webapp-cert
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
  - webapp.localhost
