apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: laravel-cert
spec:
  secretName: laravel-cert
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
  - laravel.localhost
