
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: "laravel-"
bases:
    - "../base"

patchesStrategicMerge:
  - webapp.yaml

resources:
    - "cert.yaml"
    - "pvc.yaml"

commonLabels:
  k8s.ob1.ninja/laravel-dev: "app"

