
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s.ob1.ninja/kustomize-webapp: "app"
commonAnnotations:
  k8s.ob1.ninja/kustomize-webapp: "app"

resources:
- webapp.yaml
