apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    spec:
      containers:
      - name: webapp
        image: hashicorp/http-echo:0.2.3
        args:
        - "-listen=:80"
        - "-text=webapp"
        resources:
              requests:
                  memory: "512Mi"
                  cpu: "500m"
              limits:
                  memory: "512Mi"
                  cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapp
spec:
  ports:
  # Default port used by the image
  - port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp
spec:
  rules:
  - http:
      paths:
      - path: /webapp
        backend:
          serviceName: webapp
          servicePort: 80
---